### PR TITLE
Added "in what capacity" question based on issue 9 from @dpnetca

### PR DESCRIPTION
**Pull request by fracaen**
https://github.com/dgarros/netdevops-survey/issues/9

### CODE REVIEW

**Review by dpnetca — APPROVED** [review]
Looks Good to me

**Comment by dgarros** [comment]
@fracaen  @dpnetca  Most of the questions are about the network, the tools and the current environment and not so much about who is responding, so I'm not sure if there is a lot of value to gather additional information about who is responding to the survey. I think this could open the door to more questions about who is filling the survey. (I already received some suggestions over email) . 
The last section about trends and interest is indeed specific per individual but I don't think these questions are the most important in the survey. 

since the questions are about the network and the tools supporting the network, someone should involved with multiple network should probably respond to the survey multiple times. 
 
Thoughts ?

**Comment by fracaen** [comment]
I don't feel strongly either way (as to whether we should ask this question). 
I see some limited value in understanding the respondent's capacity.
I also see value in keeping the survey short and anonymous.
@dgarros I am a little concerned about encouraging respondents to fill it out more than once. I would actually go in the opposite direction and ask that respondents pick their most significant network, and answer once with that network in mind.

**Comment by dgarros** [comment]
I will close this one since we're starting a new edition

**Pull request closed without merging**
